Map<String, String> vietnamese = {
  'WELCOME_BACK': 'Chào mừng trở lại',
  'HOME': 'Trang chủ',
  'HISTORY': 'Lịch sử',
  'PROFILE': 'Hồ sơ',
  'COMPLETE_DELIVERY': 'Giao hàng hoàn tất',
  'RETURN_DELIVERY': 'Giao hàng trả lại',
  'ACTIVE_ORDERS': 'Đơn hàng đang giao',
  'SEE_DETAILS': 'Xem chi tiết',
  'GET_DIRECTION': 'Chỉ đường',
  'ORDER_ID': 'Mã đơn : ',
  'SEE_ORDER_DETAILS': 'Xem chi tiết đơn hàng',
  'CONFIRM_DELIVERY': 'Xác nhận giao hàng',
  'CUSTOMER': 'Khách hàng',
  'ORDER_DETAILS': 'Chi tiết đơn hàng',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'Thời gian giao hàng dự kiến',
  'PAYMENT_INFO': 'Thông tin thanh toán',
  'METHOD': 'Phương thức',
  'STATUS': 'Trạng thái',
  'ORDER_SUMMERY': 'Tổng quan đơn hàng',
  'EXTRAS': 'Thêm',
  'INSTRUCTIONS': 'Hướng dẫn: ',
  'SUBTOTAL': 'Tạm tính',
  'DISCOUNT': 'Giảm giá',
  'DELIVERY_CHARGE': 'Phí giao hàng',
  'TOTAL': 'Tổng cộng',
  'CONFIRM_DELIVERY_ALERT': 'Bạn có chắc chắn xác nhận giao hàng?',
  'NO_CANCEL': 'Không, Hủy',
  'YES_CONFIRM': 'Có, Xác nhận',
  'YES_COLLECT': 'Có, Thu tiền',
  'CASH_ON_DELIVERY': 'Thanh toán khi nhận hàng',
  'ORDER_SUCCESSFULLY_DELIVERED': 'Đơn hàng đã giao thành công',
  'BACK_TO_HOME': 'Về trang chủ',
  'OPEN': 'Mở',
  'MY_PROFILE': 'Hồ sơ của tôi',
  'BRANCH': 'Chi nhánh',
  'LOG_OUT': 'Đăng xuất',
  'ERROR': 'Lỗi',
  'SUCCESS': 'Thành công',
  'CHANGE_PASSWORD': 'Đổi mật khẩu',
  'CHANGE_LANGUAGE': 'Đổi ngôn ngữ',
  'TERMS_CONDITION': 'Điều khoản & Điều kiện',
  'PRIVACY_POLICY': 'Chính sách bảo mật',
  'EDIT_PROFILE': 'Sửa hồ sơ',
  'FIRST_NAME': 'Tên',
  'LAST_NAME': 'Họ',
  'EMAIL': 'Email',
  'PASSWORD': 'Mật khẩu',
  'MOBILE_NUMBER': 'Số điện thoại',
  'UPDATE_PROFILE': 'Cập nhật hồ sơ',
  'OLD_PASSWORD': 'Mật khẩu cũ',
  'NEW_PASSWORD': 'Mật khẩu mới',
  'RETYPE_NEW_PASSWORD': 'Nhập lại mật khẩu mới',
  'DELETE_ACCOUNT': 'Xóa tài khoản',
  'PROFILE_UPDATE': 'Đã cập nhật hồ sơ',
  'PROFILE_UPDATE_SUCCESSFULLY': 'Cập nhật hồ sơ thành công',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'Cập nhật mật khẩu thành công',
  'CONFIRM_NEW_PASSWORD': 'Xác nhận mật khẩu mới',
  'PLEASE_ENTER_VALID_INPUT': 'Vui lòng nhập dữ liệu hợp lệ',
  'PRESS_BACK_AGAIN_TO_EXIT': 'Nhấn quay lại lần nữa để thoát.',
  'REMEMBER_ME': 'Ghi nhớ tôi',
  'ORDER_HISTORY': 'Lịch sử đơn hàng',
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": 'Kích thước ảnh phải dưới 2MB',
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": 'Lưu ảnh đại diện thành công',
  'SOMETHING_WRONG': 'Có lỗi xảy ra',
  "YOU_HAVE_NO_ORDER_FOR_DELIVERY": "Bạn không có đơn hàng nào để giao",
  "WAIT_NOTE": "Vui lòng đợi quản lý chi nhánh giao đơn hàng cho bạn.",
  "YOU_HAVE_NO_ORDER_HISTORY": "Bạn không có lịch sử đơn hàng",
  "ALL_BRANCH": "Tất cả chi nhánh",
  "INSTRUCTION": "Hướng dẫn",
  "DELIVERY_ADDRESS": "Địa chỉ giao hàng",
  "PAID": "Đã thanh toán",
  "UNPAID": "Chưa thanh toán",
  "PICK_PAY": "Lấy & Trả tiền",
  "DO_YOU_COLLECT_PAYMENT": "Bạn có thu tiền không?",
  "AMOUNT": "Số tiền",
  "PLEASE_TYPE_FIRST_NAME": "Vui lòng nhập tên của bạn",
  "PLEASE_TYPE_LAST_NAME": "Vui lòng nhập họ của bạn",
  "PLEASE_TYPE_EMAIL": "Vui lòng nhập email",
  "PLEASE_TYPE_OLD_PASSWORD": "Vui lòng nhập mật khẩu cũ",
  "PLEASE_TYPE_NEW_PASSWORD": "Vui lòng nhập mật khẩu mới",
  "PLEASE_RETYPE_PASSWORD": "Vui lòng nhập lại mật khẩu",
  "PASSWORD_MUST_BE_SIX": "Mật khẩu phải có ít nhất 6 ký tự",
  "ENTER_VALID_EMAIL": "Nhập email hợp lệ",
  "PLEASE_TYPE_PASSWORD": "Vui lòng nhập mật khẩu",
  "LOCATION_SERVICE_DENIED": "Dịch vụ định vị bị từ chối!",
  "LOCATION_PERMISSION_NOT_ENABLED": "Quyền định vị chưa được bật!",
  'PICK_AND_PAY': 'Lấy Và Trả Tiền',
};
